networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./backend/public/images:/usr/share/nginx/html/images
      - /etc/letsencrypt/live/irkcam.ru:/etc/letsencrypt/live/irkcam.ru
      - /etc/letsencrypt/archive/irkcam.ru:/etc/letsencrypt/archive/irkcam.ru
      - /etc/letsencrypt/renewal/irkcam.ru.conf:/etc/letsencrypt/renewal/irkcam.ru.conf
    depends_on:
      - frontend
      - backend
    networks:
     - dev
  
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend/public/images:/app/public/images
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
     - dev

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
     - dev