networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
    networks:
     - dev

  frontend:
    build:
      context: ./frontend
    networks:
     - dev