networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - /etc/letsencrypt/live/irkcam.ru:/etc/letsencrypt/live/irkcam.ru
      - /etc/letsencrypt/archive/irkcam.ru:/etc/letsencrypt/archive/irkcam.ru
      - /etc/letsencrypt/renewal/irkcam.ru.conf:/etc/letsencrypt/renewal/irkcam.ru.conf
    depends_on:
      - frontend
    networks:
     - dev

  frontend:
    build:
      context: ./frontend
    networks:
     - dev